# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8

CRATES="
	addr2line@0.22.0
	adler@1.0.2
	aho-corasick@1.1.3
	anstream@0.6.14
	anstyle-parse@0.2.4
	anstyle-query@1.1.0
	anstyle-wincon@3.0.3
	anstyle@1.0.7
	anyhow@1.0.86
	async-trait@0.1.81
	auto_impl@1.2.0
	autocfg@1.3.0
	backtrace@0.3.73
	bitflags@1.3.2
	bitflags@2.6.0
	bstr@1.9.1
	bytes@1.6.0
	cc@1.1.0
	cfg-if@1.0.0
	clap@4.5.9
	clap_builder@4.5.9
	clap_complete@4.5.7
	clap_derive@4.5.8
	clap_lex@0.7.1
	cli-table-derive@0.4.6
	cli-table@0.4.9
	colorchoice@1.0.1
	const-random-macro@0.1.16
	const-random@0.1.18
	crossbeam-deque@0.8.5
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.20
	crunchy@0.2.2
	csv-core@0.1.11
	csv@1.3.0
	dashmap@5.5.3
	dlv-list@0.5.2
	equivalent@1.0.1
	form_urlencoded@1.2.1
	futures-channel@0.3.30
	futures-core@0.3.30
	futures-io@0.3.30
	futures-macro@0.3.30
	futures-sink@0.3.30
	futures-task@0.3.30
	futures-util@0.3.30
	futures@0.3.30
	getrandom@0.2.15
	gimli@0.29.0
	glob@0.3.1
	globset@0.4.14
	hashbrown@0.14.5
	heck@0.5.0
	hermit-abi@0.3.9
	httparse@1.9.4
	idna@0.5.0
	ignore@0.4.22
	indexmap@2.2.6
	is_terminal_polyfill@1.70.0
	itoa@1.0.11
	lazy_static@1.5.0
	libc@0.2.155
	lock_api@0.4.12
	log@0.4.22
	lsp-types@0.94.1
	memchr@2.7.4
	miniz_oxide@0.7.4
	mio@0.8.11
	nu-ansi-term@0.46.0
	num_cpus@1.16.0
	object@0.36.1
	once_cell@1.19.0
	ordered-multimap@0.7.3
	overload@0.1.1
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	percent-encoding@2.3.1
	pin-project-internal@1.1.5
	pin-project-lite@0.2.14
	pin-project@1.1.5
	pin-utils@0.1.0
	proc-macro2@1.0.86
	quote@1.0.36
	redox_syscall@0.5.2
	regex-automata@0.4.7
	regex-syntax@0.8.4
	regex@1.10.5
	rust-ini@0.21.0
	rustc-demangle@0.1.24
	ryu@1.0.18
	same-file@1.0.6
	scopeguard@1.2.0
	serde@1.0.204
	serde_derive@1.0.204
	serde_json@1.0.120
	serde_repr@0.1.19
	serde_spanned@0.6.6
	sharded-slab@0.1.7
	signal-hook-registry@1.4.2
	slab@0.4.9
	smallvec@1.13.2
	socket2@0.5.7
	strsim@0.11.1
	syn@1.0.109
	syn@2.0.70
	termcolor@1.4.1
	thread_local@1.1.8
	tiny-keccak@2.0.2
	tinyvec@1.8.0
	tinyvec_macros@0.1.1
	tokio-macros@2.3.0
	tokio-util@0.7.11
	tokio@1.38.0
	toml@0.8.14
	toml_datetime@0.6.6
	toml_edit@0.22.15
	tower-layer@0.3.2
	tower-lsp-macros@0.9.0
	tower-lsp@0.20.0
	tower-service@0.3.2
	tower@0.4.13
	tracing-attributes@0.1.27
	tracing-core@0.1.32
	tracing-log@0.2.0
	tracing-subscriber@0.3.18
	tracing@0.1.40
	tree-sitter-cmake@0.5.0
	tree-sitter@0.22.6
	trim-in-place@0.1.7
	unicode-bidi@0.3.15
	unicode-ident@1.0.12
	unicode-normalization@0.1.23
	unicode-width@0.1.13
	url@2.5.2
	utf8parse@0.2.2
	valuable@0.1.0
	walkdir@2.5.0
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.8
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
	winnow@0.6.13
"

inherit cargo

DESCRIPTION="The Lsp for cmake"
HOMEPAGE="https://github.com/Decodetalkers/neocmakelsp"

if [[ ${PV} == 9999 ]]; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/Decodetalkers/neocmakelsp"
else
	SRC_URI="
		https://github.com/Decodetalkers/neocmakelsp/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
		${CARGO_CRATE_URIS}
	"
	KEYWORDS="~amd64"
fi

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	CC0-1.0 MIT Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"

QA_FLAGS_IGNORED="usr/bin/neocmakelsp"

src_unpack() {
	if [[ ${PV} == 9999 ]]; then
		git-r3_src_unpack
		cargo_live_src_unpack
	else
		cargo_src_unpack
	fi
}
