# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4

EAPI=8

CRATES="
	aho-corasick-0.7.18
	android_system_properties-0.1.4
	arbitrary-1.1.3
	arrayvec-0.4.12
	atty-0.2.14
	autocfg-1.1.0
	bit-set-0.5.3
	bit-vec-0.6.3
	bitflags-1.3.2
	block-buffer-0.10.2
	bstr-0.2.17
	bumpalo-3.10.0
	bytecount-0.6.3
	byteorder-1.4.3
	cc-1.0.73
	cfg-if-1.0.0
	chrono-0.4.22
	chrono-tz-0.6.3
	chrono-tz-build-0.0.3
	clap-3.2.17
	clap_lex-0.2.4
	colored-2.0.0
	core-foundation-sys-0.8.3
	cpufeatures-0.2.2
	crossbeam-channel-0.5.6
	crossbeam-deque-0.8.2
	crossbeam-epoch-0.9.10
	crossbeam-utils-0.8.11
	crypto-common-0.1.6
	dashmap-5.3.4
	derive_arbitrary-1.1.3
	deunicode-0.4.3
	digest-0.10.3
	dirs-4.0.0
	dirs-sys-0.3.7
	either-1.7.0
	encoding_rs-0.8.31
	encoding_rs_io-0.1.7
	env_logger-0.9.0
	fastrand-1.8.0
	fnv-1.0.7
	form_urlencoded-1.0.1
	generic-array-0.14.6
	getrandom-0.2.7
	git2-0.15.0
	globset-0.4.9
	globwalk-0.8.1
	grep-matcher-0.1.5
	grep-searcher-0.1.10
	half-1.8.2
	hashbrown-0.12.3
	heck-0.4.0
	hermit-abi-0.1.19
	hex-0.4.3
	humansize-1.1.1
	humantime-2.1.0
	iana-time-zone-0.1.44
	idna-0.2.3
	ignore-0.4.18
	indexmap-1.9.1
	instant-0.1.12
	itoa-0.4.8
	itoa-1.0.3
	jobserver-0.1.24
	js-sys-0.3.59
	lazy_static-1.4.0
	libc-0.2.131
	libgit2-sys-0.14.0+1.5.0
	libz-sys-1.1.8
	lock_api-0.4.7
	log-0.4.17
	matches-0.1.9
	memchr-2.5.0
	memmap2-0.5.6
	memoffset-0.6.5
	nodrop-0.1.14
	num-format-0.4.0
	num-integer-0.1.45
	num-traits-0.2.15
	num_cpus-1.13.1
	once_cell-1.13.0
	os_str_bytes-6.3.0
	parking_lot-0.12.1
	parking_lot_core-0.9.3
	parse-zoneinfo-0.3.0
	percent-encoding-2.1.0
	pest-2.2.1
	pest_derive-2.2.1
	pest_generator-2.2.1
	pest_meta-2.2.1
	phf-0.11.1
	phf_codegen-0.11.1
	phf_generator-0.11.1
	phf_shared-0.11.1
	pkg-config-0.3.25
	ppv-lite86-0.2.16
	proc-macro2-1.0.43
	proptest-1.0.0
	quick-error-1.2.3
	quick-error-2.0.1
	quote-1.0.21
	rand-0.8.5
	rand_chacha-0.3.1
	rand_core-0.6.3
	rand_xorshift-0.3.0
	rayon-1.5.3
	rayon-core-1.9.3
	redox_syscall-0.2.16
	redox_users-0.4.3
	regex-1.6.0
	regex-syntax-0.6.27
	remove_dir_all-0.5.3
	rustversion-1.0.9
	rusty-fork-0.3.0
	ryu-1.0.11
	same-file-1.0.6
	scopeguard-1.1.0
	serde-1.0.143
	serde_cbor-0.11.2
	serde_derive-1.0.143
	serde_json-1.0.83
	serde_yaml-0.9.9
	sha-1-0.10.0
	siphasher-0.3.10
	slug-0.1.4
	smallvec-1.9.0
	strsim-0.10.0
	strum-0.24.1
	strum_macros-0.24.3
	syn-1.0.99
	tempfile-3.3.0
	tera-1.17.0
	term_size-0.3.2
	termcolor-1.1.3
	terminal_size-0.1.17
	textwrap-0.15.0
	thiserror-1.0.32
	thiserror-impl-1.0.32
	thread_local-1.1.4
	tinyvec-1.6.0
	tinyvec_macros-0.1.0
	toml-0.5.9
	typenum-1.15.0
	ucd-trie-0.1.4
	uncased-0.9.7
	unic-char-property-0.9.0
	unic-char-range-0.9.0
	unic-common-0.9.0
	unic-segment-0.9.0
	unic-ucd-segment-0.9.0
	unic-ucd-version-0.9.0
	unicode-bidi-0.3.8
	unicode-ident-1.0.3
	unicode-normalization-0.1.21
	unsafe-libyaml-0.2.2
	url-2.2.2
	vcpkg-0.2.15
	version_check-0.9.4
	wait-timeout-0.2.0
	walkdir-2.3.2
	wasi-0.11.0+wasi-snapshot-preview1
	wasm-bindgen-0.2.82
	wasm-bindgen-backend-0.2.82
	wasm-bindgen-macro-0.2.82
	wasm-bindgen-macro-support-0.2.82
	wasm-bindgen-shared-0.2.82
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	windows-sys-0.36.1
	windows_aarch64_msvc-0.36.1
	windows_i686_gnu-0.36.1
	windows_i686_msvc-0.36.1
	windows_x86_64_gnu-0.36.1
	windows_x86_64_msvc-0.36.1
"

inherit cargo

MY_PV=${PV/_alpha/-alpha.}

DESCRIPTION="Count your code, quickly."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://tokei.rs"
SRC_URI="https://github.com/XAMPPRocky/${PN}/archive/v${MY_PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD Boost-1.0 MIT MPL-2.0 Unlicense ZLIB"
SLOT="0"
KEYWORDS="~amd64 ~x86"
S="${WORKDIR}/${PN}-${MY_PV}"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_compile() {
	cargo_src_compile --features all
}

src_install() {
	cargo_src_install --features all

	dodoc CHANGELOG.md README.md tokei.example.toml
}
